version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - os161_tools:/os161_dependencies:delegated
    command: sleep infinity
volumes:
  osdev_home:
    