version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${LOCAL_OS161_PATH}
        target: /workspace/os161/
      - osdev_home:/home/osdev
    command: sleep infinity
volumes:
  osdev_home:
    