version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: sleep infinity
volumes:
  os161_tools:
    