version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ${HOME}/.ssh
        target: /home/osdev/.ssh
      - osdev_home:/home/osdev:delegated
    command: sleep infinity
volumes:
  osdev_home:
    