version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - osdev_home:/home/osdev
    command: sleep infinity
volumes:
  osdev_home:
    