version: '1.0'
services:
  os161-workspace:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        USERNAME: osdev
        # These might need to change if the UID and GID do not match the host user
        # Check UID with `id -u <username>` and GID with `id -g <username>`
        UID: 1000
        GID: 1000
    volumes:
      # Mount source code
      - type: bind
        source: ..
        target: /workspace
      # Persist bash history
      - os161-devcontainer-bashhistory:/commandhistory:delegated
    command: sleep infinity
volumes:
  os161-devcontainer-bashhistory:
    